# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b74dc1c463108b70595d8473ae541756c299b92b3425c3ed4810b86c9072f27cb73c2244e019787bf5daaf263a3f62c3aa8ea17d6a3e32726ff8985cb550ca47

test:
  secret_key_base: 2c23ae15ca634e6f22bad8a16644cf2e444dabde48ef7d6d49c93fd2847668c13ca80e19c91e6af804ae9f586ab48f6927a08a908446f2ca2eb86ba9e117f65d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
